metricsGenerator:
  enabled: true
  config:
    storage:
      path: /var/tempo/wal
      remote_write_flush_deadline: 1m
      remote_write:
       - url: http://prometheus-operator-kube-p-prometheus.monitoring:9090/api/v1/write
storage:
  trace:
    backend: s3
    s3:
      bucket: ${tempo_s3_bucket_name}
      endpoint: s3.dualstack.us-east-2.amazonaws.com
      region: ${s3_bucket_region}
      insecure: false
serviceAccount:
  create: true
  name: null
  imagePullSecrets: []
  annotations:
    eks.amazonaws.com/role-arn: ${tempo_role_arn}

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
  configs:
  - name: default
    automatic_logging:
      backend: stdout
      roots: false

metaMonitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-operator
      prometheus: system


distributor:
  config:
    log_received_traces: true
    log_received_spans:
      enabled: true
      include_all_attributes: true

global_overrides:
  metrics_generator_processors:
    - service-graphs